name = "planetary-max"
main = "src/index.ts"
compatibility_date = "2024-09-01"
compatibility_flags = ["global_fetch_strictly_public"]
workers_dev = true
routes = [
  { pattern = "api.portal-os.com/*", zone_name = "portal-os.com" }
]

[vars]
PLANETARY_MODE = "single"
UMBRELLA_ENFORCEMENT = "strict"
MAXOS_MODULE = "local"

[build]
command = "npm run build"
